/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as MenRouteImport } from './routes/men'
import { Route as WellbeingRouteImport } from './routes/wellbeing'
import { Route as WomenRouteImport } from './routes/women'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const MenRoute = MenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => rootRouteImport,
} as any)
const WellbeingRoute = WellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/men': typeof MenRoute
  '/wellbeing': typeof WellbeingRoute
  '/women': typeof WomenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/men': typeof MenRoute
  '/wellbeing': typeof WellbeingRoute
  '/women': typeof WomenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/men': typeof MenRoute
  '/wellbeing': typeof WellbeingRoute
  '/women': typeof WomenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/business' | '/men' | '/wellbeing' | '/women'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business' | '/men' | '/wellbeing' | '/women'
  id: '__root__' | '/' | '/business' | '/men' | '/wellbeing' | '/women'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  MenRoute: typeof MenRoute
  WellbeingRoute: typeof WellbeingRoute
  WomenRoute: typeof WomenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/men': {
      id: '/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof MenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellbeing': {
      id: '/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof WellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  MenRoute: MenRoute,
  WellbeingRoute: WellbeingRoute,
  WomenRoute: WomenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
